# Конфигурация для Breast Cancer Wisconsin Dataset
dataset:
  name: "Breast Cancer Wisconsin (Diagnostic)"
  source_type: "url"
  file_path: "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"
  description: "569 образцов опухолей молочной железы с 30 признаками"
  task_type: "classification"

  # Специальная обработка для этого датасета
  special_preprocessing:
    type: "breast_cancer"
    has_header: false
    column_names: [
      "ID", "Diagnosis",
      "radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean",
      "compactness_mean", "concavity_mean", "concave_points_mean", "symmetry_mean", "fractal_dimension_mean",
      "radius_se", "texture_se", "perimeter_se", "area_se", "smoothness_se",
      "compactness_se", "concavity_se", "concave_points_se", "symmetry_se", "fractal_dimension_se",
      "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst",
      "compactness_worst", "concavity_worst", "concave_points_worst", "symmetry_worst", "fractal_dimension_worst"
    ]
    target_column: "Diagnosis"
    feature_start_col: 2  # начинаем с 3-й колонки (индекс 2)
    target_mapping: {"M": 1, "B": 0}

preprocessing:
  test_size: 0.25
  random_state: 42
  scaling: true
  stratify: true

model:
  num_rules: 5
  mf_class: "GBell"
  optim: "OriginalPSO"
  optim_params:
    epoch: 20
    pop_size: 30
    verbose: true
  reg_lambda: 0.1
  seed: 42

shap:
  # Фиксированная gamma без подбора
  gamma: 0.5
  training_epochs: 25
  batch_size: 32
  learning_rate: 0.005
  sample_size: 80  # для post-hoc SHAP

visualization:
  figure_size: [20, 16]
  style: "seaborn-v0_8"
  save_plots: true
  plot_format: "png"
  dpi: 300
